name = "projectforge"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# Using existing KV namespace from flutter-auth-api
[[kv_namespaces]]
binding = "KV"
id = "c73fae8bb0804801b6f23be7e84babe0"

[ai]
binding = "AI"